export const ProposalSectionType = {
  COVER: "COVER",
  PRESENTATION: "PRESENTATION",
  INDEX: "INDEX",
  MERAVIGLIA_NUMBERS: "MERAVIGLIA_NUMBERS",
  ACTIVATED_SERVICES: "ACTIVATED_SERVICES",
  STRATEGIC_PLAN: "STRATEGIC_PLAN",
  OPERATIONAL_ARCHITECTURE: "OPERATIONAL_ARCHITECTURE",
  FINANCIAL_PROPOSAL: "FINANCIAL_PROPOSAL",
  CASHFLOW: "CASHFLOW",
  INVESTMENT_AND_TERMS: "INVESTMENT_AND_TERMS",
  COMPARISON: "COMPARISON",
  CLOSING: "CLOSING",
} as const

export type ProposalSectionType =
  (typeof ProposalSectionType)[keyof typeof ProposalSectionType]
